
package trng.soap.service.loan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LoanEligibilityService", targetNamespace = "http://www.example.org/LoanEligibilityService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanEligibilityService {


    /**
     * 
     * @param parameters
     * @return
     *     returns trng.soap.service.loan.LoanResponse
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/LoanEligibilityService/NewOperation")
    @WebResult(name = "getLoanEligibilityResponse", targetNamespace = "http://www.example.org/LoanEligibilityService/", partName = "parameters")
    public LoanResponse newOperation(
        @WebParam(name = "getLoanEligibility", targetNamespace = "http://www.example.org/LoanEligibilityService/", partName = "parameters")
        LoanRequest parameters);

}
